### ISSUE TITLE
ValueError: 'null' is not of type 'integer'

### ISSUE THREAD

**Issue by vinyll** [SocialGouv/egapro-api#16]
```
PUT http://localhost:2626/declaration/123456550/2019 {
"déclarant.nom":"Agnano",
"déclarant.prénom":"Vincent",
"déclarant.téléphone":"0644393949",
"entreprise.région":"27",
"entreprise.département":"39",
"entreprise.adresse":"Rue Soret",
"entreprise.code_postal":"10221",
"entreprise.commune":"Geneve"
}
```

returns `ValueError: 'null' is not of type 'integer'`

### Traceback

```
Rolling on http://127.0.0.1:2626
Traceback (most recent call last):
  File "/Users/vinyll/Projects/egapro/api/egapro/schema/__init__.py", line 28, in validate
    JSON_SCHEMA.validate(data)
jsonschema_rs.ValidationError: 'null' is not of type 'integer'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/vinyll/Projects/egapro/api/venv/lib/python3.8/site-packages/roll/__init__.py", line 77, in __call__
    await handler(request, response, **request.route.vars)
  File "/Users/vinyll/Projects/egapro/api/egapro/views.py", line 108, in wrapper
    ret = await view(request, response, *args, **kwargs)
  File "/Users/vinyll/Projects/egapro/api/egapro/views.py", line 95, in wrapper
    return await view(request, response, siren, year, *args, **kwargs)
  File "/Users/vinyll/Projects/egapro/api/egapro/views.py", line 126, in declare
    schema.validate(data.raw)
  File "/Users/vinyll/Projects/egapro/api/egapro/schema/__init__.py", line 30, in validate
    raise ValueError(err)
```

**Comment by vinyll** [comment]
Running this with an older commit could expose that the siren was a missing required property.

I guess a good resolution would be to get the error message specific again.

**Comment by yohanboniface** [comment]
For the record https://github.com/Stranger6667/jsonschema-rs/issues/144
